############# English navigation ##############

# main menu

[[main]]
name = "Megathread"
url = "getting-started/basics/"
weight = 1

[[main]]
name = "Faq"
url = "faq/"
weight = 2


# footer menu
[[footer_primary]]
name = "Changelog"
url = "changelog/"
weight = 1

[[footer_primary]]
name = "Contact us"
url = "contact/"
weight = 2